# Generated by Django 2.1 on 2018-09-04 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pqr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('', ''), (1, 'Queja'), (2, 'Peteicion'), (3, 'Reclamo'), (4, 'Sugerencia'), (5, 'Felicitacion')], max_length=15)),
                ('comentario', models.TextField(blank=True, max_length=1000)),
                ('estado', models.CharField(blank=True, choices=[('', ''), (1, 'Solucionado'), (2, 'Sin Resolver'), (3, 'En Proceso')], max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifacion', models.DateField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.Perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['motivo'],
            },
        ),
    ]
