# Generated by Django 2.1 on 2018-08-30 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coopropiedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inmueble', models.CharField(choices=[('', ''), (1, 'Casa'), (2, 'Apartemento'), (3, 'Duplex'), (4, 'PentHouses'), (5, 'Parcela')], max_length=15)),
                ('nombre_inmueble', models.CharField(help_text='Apto 102, Casa 3', max_length=50)),
                ('nombre_propietario', models.CharField(help_text='Nombre(s)', max_length=50)),
                ('apellidos_propietario', models.CharField(help_text='Apellido(s)', max_length=50)),
                ('telefono', models.CharField(help_text='Numero de contacto', max_length=50)),
                ('correo', models.CharField(help_text='Correo electronico', max_length=50)),
                ('grupo', models.CharField(choices=[('', ''), (1, 'Junta'), (2, 'Consejo')], max_length=15)),
                ('fecha_inicio_residencia', models.DateField(blank=True, null=True)),
                ('coopropiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles', to='coopropiedad.Coopropiedad')),
            ],
            options={
                'ordering': ['-nombre_inmueble'],
            },
        ),
    ]
