# Generated by Django 2.1 on 2018-08-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inmueble', models.CharField(choices=[('', ''), ('casa', 'Casa'), ('apartamento', 'Apartemento'), ('duplex', 'Duplex'), ('penthouses', 'PentHouses'), ('parcela', 'Parcela')], max_length=10)),
                ('nombre_inmueble', models.CharField(help_text='Apto 102, Casa 3', max_length=50)),
                ('nombre_propietario', models.CharField(help_text='Nombre(s)', max_length=50)),
                ('apellidos_propietario', models.CharField(help_text='Apellido(s)', max_length=50)),
                ('telefono', models.CharField(help_text='Numero de contacto', max_length=50)),
                ('correo', models.CharField(help_text='Correo electronico', max_length=50)),
                ('grupo', models.CharField(choices=[('', ''), ('propietario', 'Propietario'), ('arrendatario', 'Arrendatario'), ('inmobiliaria', 'Inmobiliaria'), ('junta', 'Junta'), ('consejo', 'Consejo')], max_length=10)),
            ],
            options={
                'ordering': ['-nombre_inmueble'],
            },
        ),
    ]
