# Generated by Django 2.1 on 2018-10-04 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copropiedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inmueble', models.CharField(choices=[('', ''), ('casa', 'Casa'), ('apartamento', 'Apartamento'), ('duplex', 'Duplex'), ('penthouses', 'PentHouses'), ('parcela', 'Parcela')], max_length=15)),
                ('nombre', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('bloque', models.CharField(max_length=10)),
                ('observacion', models.TextField(max_length=1000)),
                ('fecha_construcion', models.DateField()),
                ('copropiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles', to='copropiedad.Copropiedad')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
