# Generated by Django 2.1 on 2018-08-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.CharField(choices=[('', ''), ('casa', 'Casa'), ('apartamento', 'Apartemento'), ('duplex', 'Duplex'), ('penthouses', 'PentHouses'), ('parcela', 'Parcela')], max_length=15),
        ),
    ]
