# Generated by Django 2.1 on 2018-08-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0003_inmueble_coopropiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='fecha_inicio_residencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='grupo',
            field=models.CharField(choices=[('', ''), ('junta', 'Junta'), ('consejo', 'Consejo')], max_length=15),
        ),
    ]
