# Generated by Django 2.1 on 2018-09-04 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmueble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(choices=[('', ''), (1, 'Arrendatario'), (2, 'Junta'), (3, 'Consejo')], default=0, max_length=15)),
                ('fecha_inicio', models.DateField(blank=True)),
                ('fecha_final', models.DateField(blank=True)),
                ('es_propietario', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False)),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles', to='inmueble.Inmueble')),
            ],
            options={
                'ordering': ['grupo'],
            },
        ),
    ]
