# Generated by Django 2.1 on 2018-08-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmueble', '0004_auto_20180819_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_residente', models.CharField(help_text='Nombre(s) residente', max_length=50)),
                ('apellidos_propietario', models.CharField(help_text='Apellido(s) residente', max_length=50)),
                ('telefono', models.CharField(help_text='Numero de contacto', max_length=50)),
                ('correo', models.CharField(help_text='Correo electronico', max_length=50)),
                ('grupo', models.CharField(choices=[('', ''), ('arrendatario', 'Arrendatario'), ('junta', 'Junta'), ('consejo', 'Consejo')], max_length=15)),
                ('fecha_inicio_residencia', models.DateField(blank=True, null=True)),
                ('arrendador', models.CharField(choices=[('', ''), (True, 'Si'), (False, 'No')], max_length=6)),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles', to='inmueble.Inmueble')),
            ],
            options={
                'ordering': ['-nombre_residente'],
            },
        ),
    ]
