# Generated by Django 2.1 on 2018-08-18 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmueble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coopropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_coopropiedad', models.CharField(help_text='Nombre del condominio', max_length=50)),
                ('direccion', models.CharField(help_text='Direccion del condominio', max_length=30)),
                ('telefono', models.CharField(help_text='Numero telefonico del condominio', max_length=50)),
                ('nit', models.CharField(help_text='NIT del condominio', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripcion del condominio', max_length=200)),
                ('inmuebles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles', to='inmueble.Inmueble')),
            ],
            options={
                'ordering': ['-nombre_coopropiedad'],
            },
        ),
    ]
