# Generated by Django 2.1 on 2018-08-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coopropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_coopropiedad', models.CharField(help_text='Nombre del condominio', max_length=50)),
                ('direccion', models.CharField(help_text='Direccion del condominio', max_length=30)),
                ('telefono', models.CharField(help_text='Numero telefonico del condominio', max_length=50)),
                ('nit', models.CharField(help_text='NIT del condominio', max_length=20)),
                ('descripcion', models.TextField(help_text='Descripcion del condominio', max_length=200)),
            ],
            options={
                'ordering': ['nombre_coopropiedad'],
            },
        ),
    ]
