# Generated by Django 2.1 on 2018-10-04 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('rol', models.CharField(choices=[(0, ''), (1, 'Habitante'), (2, 'Administrador'), (3, 'Revisor Fiscal'), (4, 'Administrador'), (5, 'Contador'), (6, 'Presidente'), (7, 'Tesorero'), (8, 'Proveedor')], max_length=20)),
                ('foto', models.ImageField(upload_to='usuarios/fotos')),
                ('codigo_invitacion', models.CharField(blank=True, max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modifacion', models.DateField(auto_now=True)),
                ('usuraio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
